default: &default
  adapter: postgresql
  pool:    5
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch "DB_NAME" %>_development

production:
  <<: *default
  database: <%= ENV.fetch "DB_NAME" %>_production

test:
  <<: *default
  database: <%= ENV.fetch "DB_NAME" %>_test
